wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1637938193
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 15
      - 17
      4: 3.8.12
      5: 0.12.5
      8:
      - 1
      - 3
      - 5
