wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1637949278
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 17
      4: 3.8.12
      5: 0.12.5
      8:
      - 1
      - 3
      - 5
    viz:
      calibration_curve:
        historyFieldSettings:
          key: calibration_curve
          x-axis: _step
        id: wandb/calibration/v1
      class_proportions:
        historyFieldSettings:
          key: class_proportions
          x-axis: _step
        id: wandb/class_proportions/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      feature_importances:
        historyFieldSettings:
          key: feature_importances
          x-axis: _step
        id: wandb/feature_importances/v1
      precision_recall:
        historyFieldSettings:
          key: precision_recall
          x-axis: _step
        id: wandb/pr_curve/v1
      roc:
        historyFieldSettings:
          key: roc
          x-axis: _step
        id: wandb/roc/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
